### PR TITLE
fix(idempotency): deep sort payload during hashing

### PR DESCRIPTION
**Pull request by arnabrahman**
## Summary

According to the [Issue](https://github.com/aws-powertools/powertools-lambda-typescript/issues/2120), payloads containing the exact same keys should be considered idempotent regardless of their order. 

For example, these two requests should be idempotent.

```
const requestA = {
  name: "John",
  age: 30,
  city: "New York",
  address: {
    street: "5th Avenue",
    number: 123,
  },
};

const requestB = {
  city: "New York",
  name: "John",
  age: 30,
  address: {
    number: 123,
    street: "5th Avenue",
  },
};
```

The same goes for JSON arrays, the following two requests should be idempotent.

```
const requestA = [{
  a: 30,
  c: "John",
  b: "New York",
}]

const requestB = [{
  a: 30,
  b: "New York",
  c: "John"
}];
```
To achieve this, we need to implement a function that deep sorts the payload & use it to sort the payload before generating the hash.

### Changes

Implement a function that recursively sorts the keys of an object or elements of an array. The function is based on [this blog post](https://whitfin.io/blog/sorting-object-recursively-node-jsjavascript/) that was mentioned in the issue description. In addition, added support for sorting objects inside JSON array. 

- Uses `getType` from `@aws-lambda-powertools/commons` to determine the input data type.
- For objects, it sorts the keys alphabetically in a case-insensitive manner using sortObject.
- For arrays, it recursively applies deepSort to each element.
- Primitives are returned unchanged.

Used this function before generating hash inside `BasePersistenceLayer` class. 

Also, written unit tests for the function for different scenarios that I can think of. I couldn't find a method in `jest` that checks if two objects are equal and ensures that the key positions are similar. Therefore, I used `JSON.stringify` to compare the two objects.

I am not sure if I need to update any documentation for this. Please let me know if I need to make any tweaks.

**Issue number:** #2120

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Review by dreamorosi — CHANGES_REQUESTED** [review]
The integration tests for this branch [are failing](https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/9192311915/job/25280659348#step:8:523) because the sorting changes the hashes/idempotency ID generated for some of the tests.

I have also left a couple comments in the code.

**Comment by dreamorosi** [comment]
Thank you for the PR @arnabrahman, appreciate it!

**Comment by am29d** [comment]
I agree that this is a necessary change and improves idempotency utility and this is a breaking change. As you said, this could disable idempotency for some cases which can lead to severe impact on the customer side.

**Comment by arnabrahman** [comment]
@dreamorosi for the e2e tests, i couldn't run it locally but maybe we need to `deepSort` the record before stringify. https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/idempotency/tests/e2e/makeIdempotent.test.ts#L177

**Comment by dreamorosi** [comment]
@arnabrahman that's right, I believe that if we sort these payloads the tests should pass. 

Please bear with us while we agree on a way forward - I'm unsure whether this should be considered a bug fix or a new feature, in which case it might be a breaking change.

Also what do you think?

**Comment by arnabrahman** [comment]
@dreamorosi , this is a peculiar situation. At a high level, this sounds like a bug fix.

However, from my experience, I don't recall ever sorting a payload of objects before sending it. I might have done so unintentionally, but never intentionally. I believe that in the majority of cases, this change will cause issues. So, from a customer's perspective, this is a `Breaking Change`.

If so, in my opinion, we cannot say it's a bug fix.

**Comment by dreamorosi** [comment]
I see where you're coming from. 

Imo the fact that we were not ordering the payload, especially since Powertools for AWS Lambda (Python) does it, was not intended and even though the change could cause unintended side effects, these are only the results of us not sorting the payload in the first place.

Like you said, sorting is not something customers would (nor should) think about it, but requests with the same payload content should be idempotent, so the fact that this wasn't the case maybe makes it a bug.

**Comment by dreamorosi** [comment]
Putting this on hold until @heitorlessa is back to advise on how to move forward.

**Comment by heitorlessa** [comment]
Take it as a bug fix, as this shouldn't have passed in our tests suite. There are internet proxies and the fact a client or a proxy could interfere with the guaranteed idempotency within a time window makes this a serious bug.

example: If we were changing the idempotency key format, I'd consider as a breaking change. 

Here, it'll cause bigger harm for new customers having mixed results without any way to debug it. In the worst case, we know > 90% of customers don't change the defaults, so idempotency records will expire within an hour.. reducing the impact window for the bugfix.

**Pull request merged**
