### PR TITLE
feat(idempotency): ability to specify JMESPath custom functions

### PR DESCRIPTION
**Pull request by arnabrahman**
## Summary
According to the Issue description, customers should be able to send their custom JMESPatch functions instead of built-in ones using the idempotency utility.
### Changes

- Introduce a new option `jmesPathOptions` in `IdempotencyOptions`
- Export `Functions` to use it type the `jmesPathOptions`
- Set the custom functions from config if present
- Write unit tests for the new option
- Update the docs for the new options but as always need suggestions on this.

**Issue number:** #2368 

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by dreamorosi** [comment]
Hey @arnabrahman, thank you for the PR!

Before I get into the review, I wanted to ask if you're still seeing the issue with coverage on the git hooks described here #3134.

I've tried reproducing it on my side and I can't.

**Comment by arnabrahman** [comment]
Yesterday, when I was pushing the commits, I faced the coverage issue again. After that, for all subsequent commits, I used the skip flag, as far as I remember.

Another thing, I believe my main branch was behind when I encountered this issue. After merging the main branch, I don’t recall if I tried committing without the skip flag. I’ll try again and get back to you @dreamorosi

**Comment by arnabrahman** [comment]
Nope, the test coverage error is not there anymore.

**Comment by dreamorosi** [comment]
Thank you @arnabrahman - I'm still going to do a small adjustment to the git hook because right now they're trying to run also e2e tests, which we don't want to.

Next time that it happens, if you can, please try to remove this flag `--changed="$(git merge-base HEAD main)"` and see if it fixes it. I have a suspect that it might be the reason why it's happening.

---

I'll review the PR in the next couple hrs tops.

**Review by dreamorosi — APPROVED** [review]
Thank you for adding this feature, I appreciate your time and effort on this.

I have run the e2e tests on this branch and they are [successful](https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/11184110900).

**Pull request merged**
