### PR TITLE
chore: add @middy/core v6 as peer dependency

### LINKED ISSUE #3367: Feature Request: add support for Middy.js 6.x
### Expected Behavior

You can install v6.x of @middy/core and @aws-lambda-powertools/logger

### Current Behavior

When installing v6.x of @middy/core you get this error 

```
 npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @aws-lambda-powertools/logger@2.11.0
npm ERR! Found: @middy/core@6.0.0
npm ERR! node_modules/@middy/core
npm ERR!   @middy/core@"^6.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @middy/core@"4.x || 5.x" from @aws-lambda-powertools/logger@2.11.0
npm ERR! node_modules/@aws-lambda-powertools/logger
npm ERR!   @aws-lambda-powertools/logger@"^2.11.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @middy/core@5.5.1
npm ERR! node_modules/@middy/core
npm ERR!   peerOptional @middy/core@"4.x || 5.x" from @aws-lambda-powertools/logger@2.11.0
npm ERR!   node_modules/@aws-lambda-powertools/logger
npm ERR!     @aws-lambda-powertools/logger@"^2.11.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Code snippet

in package.json

```
  "dependencies": {
    "@aws-lambda-powertools/logger": "^2.11.0",
    "@middy/core": "^6.0.0",
```

### Steps to Reproduce

Install @middy/core v6 and @aws-lambda-powertools/logger

### Possible Solution

change peerDepenedencies in @aws-lambda-powertools/logger to include v6 of @middy/core

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

22.x

### Packaging format used

npm

### Execution logs

```Shell

```

### PR DESCRIPTION
**Pull request by anthony-nhs**
### Changes

> Please provide a summary of what's being changed
This PR adds @middy/core v6 as a peer dependency

You can not use @powertools-lambda-typescript and @middy/core v6 

> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed

**Issue number:**  Closes #3367

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Review by dreamorosi — CHANGES_REQUESTED** [review]
Thank you for opening this PR.

I don't think doubling the amount of tests we run only to add Middy.js is the way to go as this doubles or more our feedback loop.

I would propose to instead use Middy.js v6 [to this test only](https://github.com/aws-powertools/powertools-lambda-typescript/blob/aafa4c971b7038047da9e4f420391def8f304377/packages/idempotency/tests/e2e/makeHandlerIdempotent.test.FunctionCode.ts#L2), plus one that we will add in a future PR for the Metrics utility.

This way we'll have a somewhat even distribution of tests running v4, v5, and v6 without having to repeat tests.

**Comment by anthony-nhs** [comment]
ok - have changed it so that only one test is changed to use middy v6

**Comment by dreamorosi** [comment]
Thank you for addressing the comment.

Tomorrow morning (EU time) I'll run some more in depth manual tests and familiarize myself with the changes in v6.

If there's no blocker and CI is green I'll merge this PR so that the change can land in the next release.

**Review by dreamorosi — COMMENTED** [review]
Thank you for your patience.

I ran the end to end tests on this branch and [they're green](https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/12083889005). 

I also looked at the [v6 release notes](https://github.com/middyjs/middy/releases/tag/6.0.0) and commit history, and there seems not to be any breaking change in the core module that would affect us.

I'm happy to merge this as-is and update the docs later.

**Review by dreamorosi — APPROVED** [review]

**Pull request merged**
