### PR TITLE
chore(idempotency): remove decorators

### PR DESCRIPTION
**Pull request by dreamorosi**
## Description of your changes

As described in the linked issue, this PR removes the Idempotency decorators from the current implementation which will be soon released as public beta. For more info on why we decided to remove them, please refer to #1553.

### Related issues, RFCs

**Issue number:** #1553

## Checklist

- [x] [My changes meet the tenets criteria](https://docs.powertools.aws.dev/lambda-typescript/#tenets)
- [x] I have performed a *self-review* of my own code
- [ ] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [ ] I have made corresponding changes to the *documentation*
- [x] My changes generate *no new warnings*
- [ ] I have *added tests* that prove my change is effective and works
- [x] The PR title follows the [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

***Is it a breaking change?:*** NO

- [ ] I have documented the migration process
- [ ] I have added, implemented necessary warnings (if it can live side by side)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by dreamorosi** [comment]
@mergify rebase

**Comment by dreamorosi** [comment]
Successful integration tests: https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/5391493794

**Comment by am29d** [comment]
We should probably also remove references in the documentation.

**Comment by dreamorosi** [comment]
Good catch Alex, I have updated the README and removed all references.

While there, I also added a section for the Middy Middleware and consolidated the examples under their respective title.
Before it was:
- Usage
  - Function wrapper
  - Middy middleware
- Examples
  - Function wrapper
  - Middy middleware

Now it's
- Usage
  - Function wrapper
    - Example
  - Middy middleware
    - Example

Also, I noticed that the `DynamoDBPersitenceLayer` and its options were not exported in the API docs, I added it and did a find&replace for `s/persistance/persistence/` which was used in some places.

Finally, as a side note, I noticed that when we use intersection types the documentation for those resulting types is not rendered correctly. For instance, even though we wrote the docstring for `DynamoDBPersistenceOptions`, it's rendered empty:
image

This is because the actual properties are in the base type.

Apparently this is an intended behavior in typedoc: https://github.com/TypeStrong/typedoc/issues/1021. For now I added a `@see` and exported+linked the actual types but in a separate issue we should look into whether there's a solution for this.

**Comment by dreamorosi** [comment]
@am29d addressed the comments, ready for review

**Review by am29d — APPROVED** [review]
LGTM!

**Pull request merged**
