### PR TITLE
chore(idempotency): expiration timestamp rounded to the nearest second 

### PR DESCRIPTION
**Pull request by arnabrahman**
## Summary

For consistency, we need to align timestamp formats for `expiration` and `in_progress_expiration` in idempotency table. To achieve this we have to round off `expiration` attribute.

### Changes

- Round off the return value of `getExpiryTimestamp` function
- Fix failing tests because of the rounding off

**Issue number:**  #2298

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by dreamorosi** [comment]
Hi @arnabrahman - thank you for opening this PR!

While I review it and run tests, could I please ask you to leave a comment under the linked issue so that I can assign it to you? (GitHub doesn't let me do it unless you interact with it first).

**Comment by arnabrahman** [comment]
Regarding the failing integration test, it's possible that the sorting order is being affected because we are rounding off the `expiration` value.

https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/idempotency/tests/e2e/makeIdempotent.test.ts#L205-L207

For example, previously if this was the `items` array with `expiryAttr`:
```
const items = [
      { id: 1, foo: 'bar' , expiryAttr: 0.6},
      { id: 2, foo: 'baq' , expiryAttr: 0.7},
      { id: 3, foo: 'bar' , expiryAttr: 0.8},
],
```
After sorting, the `items` array would remain `unchanged`.

But now, if the value is rounded off, the `items` array would look like this for the same value:

```
const items = [
      { id: 1, foo: 'bar' , expiryAttr: 1},
      { id: 2, foo: 'baq' , expiryAttr: 1},
      { id: 3, foo: 'bar' , expiryAttr: 1,
],
```
And after sorting, the `items` array will look like this:
```
const items = [
      { id: 3, foo: 'bar' , expiryAttr: 1},
      { id: 2, foo: 'baq' , expiryAttr: 1},
      { id: 1, foo: 'bar' , expiryAttr: 1},
],
```
This is likely why we get `id: 3` in the first position. (https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/9195366267/job/25291037147#step:8:538)

However, I'm not entirely certain. To validate this, need the actual values for `expiryAttr` in `e2e`.

@dreamorosi

**Comment by dreamorosi** [comment]
Thank you for looking into it, you are exactly right.

I have tested this on my local branch and it works, I'd suggest to replace the sorting [here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/fe92fef2829955427d5adb9e1f1b58320986b22b/packages/idempotency/tests/e2e/makeIdempotent.test.ts#L205-L207) with this:

```ts
const idempotencyRecordsItems = [
  idempotencyRecords.Items?.find(
    (record) =>
      record.customId ===
      `${functionNameCustomConfig}#${payloadHashes[0]}`
  ),
  idempotencyRecords.Items?.find(
    (record) =>
      record.customId ===
      `${functionNameCustomConfig}#${payloadHashes[1]}`
  ),
  idempotencyRecords.Items?.find(
    (record) =>
      record.customId ===
      `${functionNameCustomConfig}#${payloadHashes[2]}`
  ),
];
```

and the one [here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/fe92fef2829955427d5adb9e1f1b58320986b22b/packages/idempotency/tests/e2e/makeIdempotent.test.ts#L140-L142) with this:

```ts
const idempotencyRecordsItems = [
  idempotencyRecords.Items?.find(
    (record) => record.id === `${functionNameDefault}#${payloadHashes[0]}`
  ),
  idempotencyRecords.Items?.find(
    (record) => record.id === `${functionNameDefault}#${payloadHashes[1]}`
  ),
];
```

Once replaced I'll run the tests again and if green, I think we should be able to merge!

**Comment by arnabrahman** [comment]
I have updated the tests. You can try it now, @dreamorosi

**Comment by dreamorosi** [comment]
Thank you - seems to[ work now](https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/9235158202), great job!

**Review by dreamorosi — APPROVED** [review]
Thank you so much for this PR and for iterating on the feedback.

**Pull request merged**
