### PR TITLE
docs: typo for serverless framework

### LINKED ISSUE #1706: Docs: typo aws::region in serverless framework and terraform
### What were you searching in the docs?

The example of powertools with serverless framework has incorrect syntax for aws region variable: 

```yaml
functions:
  hello:
    handler: lambda_function.lambda_handler
    layers:
      - arn:aws:lambda:${aws::region}:094274105915:layer:AWSLambdaPowertoolsTypeScript:19
```

Keen in mind that we need to update the script in the workflow, so we can replace increment the layer version in the docs during release.

https://github.com/aws-powertools/powertools-lambda-typescript/blob/06815118da45973d69b2c57124cf0ccd5255c88a/.github/scripts/update_layer_arn.sh#L59

### Is this related to an existing documentation section?

Getting started

### How can we improve?

```Markdown
Review all the `aws::region` variables, including terraform.
```

### Got a suggestion in mind?

_No response_

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

### PR DESCRIPTION
**Pull request by HaaLeo**
## Description of your changes

According to the docs it should be {aws:region} [Reference](https://www.serverless.com/framework/docs/providers/aws/guide/variables/#referencing-aws-specific-variables)

### Related issues, RFCs

**Issue number:**  #1706 

## Checklist

- [x] [My changes meet the tenets criteria](https://docs.powertools.aws.dev/lambda-typescript/#tenets)
- [x] I have performed a *self-review* of my own code
- [x] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [x] I have made corresponding changes to the *documentation*
- [x] My changes generate *no new warnings*
- [x] I have *added tests* that prove my change is effective and works
- [x] The PR title follows the [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

***Is it a breaking change?:*** NO

- [ ] I have documented the migration process
- [ ] I have added, implemented necessary warnings (if it can live side by side)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Review by am29d — CHANGES_REQUESTED** [review]
Thanks for PR fixing the typo. I have added the issue #1706 . 

We need also to adjust the update layer script [here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/06815118da45973d69b2c57124cf0ccd5255c88a/.github/scripts/update_layer_arn.sh#L59) so we can update the layer version in the docs. Could you please change this file as well?

**Comment by HaaLeo** [comment]
Hi @am29d, thx for creating the issue. I've updated the script as well. 
You can review once more. :)

**Review by am29d — APPROVED** [review]
Thanks @HaaLeo for the PR 🙏 .

**Comment by am29d** [comment]
Hey @HaaLeo , apologies for the merge conflict, I have approved the PR during a minor release and it changed the `index.md` during the layer version update. Can I ask you to resolve the conflict this last time, then we can merge it and update the docs (we can update docs outside of release cycle).

**Review by am29d — APPROVED** [review]

**Comment by HaaLeo** [comment]
@am29d now it should be good to go

**Review by am29d — APPROVED** [review]

**Pull request merged**
