### PR TITLE
improv(commons): add number key type to JSONObject type

### LINKED ISSUE #1689: JSONObject should support narrowing to `[key: number]:JSONValue`
### Use case

Behind the scenes, javascript converts numeric keys to strings. The pattern `object[1234]` is valid. However, JSONObject is defined as `[key: string]: JSONValue` and the result of getMultiple (dynamodb provider) cannot be cast into a type like `[key: number] : JSONValue` since `string` cannot be narrowed to `number`.

The type being used expects it to be a number, because that is how the parameter is accessed.

You can do `object[1234]` today without this change because TypeScript knows about the behavior of numbers being converted to strings. This is simply about narrowing the type to only allow numbers. 

### Solution/User Experience

Update JSONObject to the following type: `type JSONObject = { [key: string | number]: JSONValue; }`

This way a type can narrow `JSONObject` to `[key: number]:JSONValue`.

### Alternative solutions

_No response_

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

### PR DESCRIPTION
**Pull request by KhurramJalil**
Fixes #1689

### Related issues, RFCs

**Issue number**: closes #1689

## Checklist

- [x] [My changes meet the tenets criteria](https://docs.powertools.aws.dev/lambda-typescript/#tenets)
- [x] I have performed a *self-review* of my own code
- [x] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [ ] I have made corresponding changes to the *documentation*
- [x] My changes generate *no new warnings*
- [ ] I have *added tests* that prove my change is effective and works
- [x] The PR title follows the [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

***Is it a breaking change?:*** NO

- [ ] I have documented the migration process
- [ ] I have added, implemented necessary warnings (if it can live side by side)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by dreamorosi** [comment]
Hi @KhurramJalil thanks for opening this issue. 

The PR is being labeled as `do-not-merge`, as well as having a failed check due to the following reasons:
- (`do-not-merge`) out automation is not detecting any related issue in the PR body. I see that you have linked the issue, however you've done so outside of the expected format, which is why it's failing. For reference, this is the relevant part of the PR template:

```md
### Related issues, RFCs

<!--- 
Add here the number (i.e. #42) to the Github Issue or RFC that is related to this PR.

Don't include any other text, otherwise the Github Issue will not be detected.

Note: If no issue is present the PR might get blocked and not be reviewed.
-->
**Issue number:** 
```

The issue number should have gone near `**Issue number:**`, so once filled it'd be like this:

```diff
### Related issues, RFCs

<!--- 
Add here the number (i.e. #42) to the Github Issue or RFC that is related to this PR.

Don't include any other text, otherwise the Github Issue will not be detected.

Note: If no issue is present the PR might get blocked and not be reviewed.
-->
-- **Issue number:** 
++ **Issue number:** closes #1689
```

- (failed check) the PR title does not follow the expected format/convention. We use conventional commit semantics for PR titles as this allows us to version our project based on the squashed merge commits. The last checkbox that you have marked in the PR body is about this and has a link with examples of allowed keywords. In this case I'd suggest changing the title to something like "improv(commons): add `number` key type to `JSONObject` type".

Once the issues above have been fixed I'll be happy to approve & merge the PR 😃

**Review by dreamorosi — CHANGES_REQUESTED** [review]
Hi @KhurramJalil thanks again for the PR, please review the comment above and let me know if you need any additional help.

**Comment by KhurramJalil** [comment]
Thanks for your kind review and feedback @dreamorosi. I have taken care of both the feedback points.

- Included issue number in the right format at the right place
- Updated the title of the PR as per recommended standard

> Hi @KhurramJalil thanks again for the PR, please review the comment above and let me know if you need any additional help.

**Review by dreamorosi — APPROVED** [review]
Thank you for addressing all the comments, I've made a small edit to the title to remove the content of the old one.

Other than that, it's good to go. Congrats on your first PR merged in this project 🎉

**Pull request merged**
