### PR TITLE
chore(layers): add Parser to layer

### PR DESCRIPTION
**Pull request by scratchclaggy**
## Summary

Small PR to add the new parser feature to the published lambda layers.

### Changes

> Please provide a summary of what's being changed

Adds the feature to the layer stacks in the layer package.

> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed

**Issue number:** #3100

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by scratchclaggy** [comment]
This is my first PR against this project, so please let me know if I am missing anything here.

Also, could someone please confirm that the changes from this PR will trigger a new layer to be built, and following this the documentation will be updated automatically.

**Review by dreamorosi — CHANGES_REQUESTED** [review]
Hi @scratchclaggy, thank you for the PR.

The utility doesn't come with Zod by default, so we need to install it.

You should add it to the block around line 110.

**Comment by am29d** [comment]
Hey @scratchclaggy, can you also add the package to our e2e tests. We usually check if the package is present and can be imported. 

While we invoke some of the utilities in our [canary lambda directly](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/layers/tests/e2e/layerPublisher.class.test.functionCode.ts), i.e. logger and metrics. I think we can also run a parse small parse command with a fairly trivial payload, just to be sure that it's safe.

**Review by am29d — APPROVED** [review]
Looks good, thanks for adding the tests!

**Review by dreamorosi — APPROVED** [review]

**Pull request merged**
