### PR TITLE
chore(ci): remove GH pages

### PR DESCRIPTION
**Pull request by sthulb**
## Description of your changes

Remove GH pages from GH actions. We no longer use GH pages, as we have migrated to our new docs hosting already.

### Related issues, RFCs

**Issue number:** #1509

## Checklist

- [x] [My changes meet the tenets criteria](https://docs.powertools.aws.dev/lambda-typescript/#tenets)
- [x] I have performed a *self-review* of my own code
- [x] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [x] I have made corresponding changes to the *documentation*
- [x] My changes generate *no new warnings*
- [x] I have *added tests* that prove my change is effective and works
- [x] The PR title follows the [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

***Is it a breaking change?:*** NO

- [ ] I have documented the migration process
- [ ] I have added, implemented necessary warnings (if it can live side by side)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by dreamorosi** [comment]
@sthulb are we still keeping the `gh-pages` branch around or just building the docs and publishing them?

Also can you please take a look at the comment in #1509 and sync the versions? I could manually push the `versions.json` file to the bucket but that might not be the best way to fix it.

**Comment by sthulb** [comment]
> @sthulb are we still keeping the `gh-pages` branch around or just building the docs and publishing them?

just building and pushing to S3. There’s no need to keep the branch. The backup-GH-pages branch exists as a part of the transition. 

> 
> Also can you please take a look at the comment in #1509 and sync the versions? I could manually push the `versions.json` file to the bucket but that might not be the best way to fix it.

versions.json will be addressed in a PR tomorrow. I have to do the same for python too

**Comment by dreamorosi** [comment]
Ok, I don't know `mkdocs` and `mike` enough so I'll leave this to you.

**Review by dreamorosi — COMMENTED** [review]
Removing these steps only removes the publishing of the API folder (aka API docs), the actual docs written with `mkdocs` are still being pushed to the `gh-pages` (currently `backup-gh-pages`) branch by `mike` at [L81-83](https://github.com/aws-powertools/powertools-lambda-typescript/blob/5d035a1d4597d9036cdc4ea58a10b046b8a67f52/.github/workflows/reusable-publish-docs.yml#L81-L84).

Did you leave them on purpose?

Also, if we remove the branch entirely (which I think we should), I'm not sure how the workflow is going to be able to manage the `versions.json`. My understanding is that currently `mike` relies on the presence of this file in the other branch, and when creating a new version/alias it appends it to the file.

If the branch is removed, then we need to make sure `mike` is able to handle the file that is now present in S3.

**Comment by dreamorosi** [comment]
@sthulb given #1521 should we remove `mike` entirely from both the workflow & the `docs/requirements.txt` file?

**Comment by dreamorosi** [comment]
Hey @sthulb, can we remove `mike deploy --push --update-aliases --no-redirect ${{ env.VERSION }} ${{ env.ALIAS }} --branch backup-gh-pages` and `mike set-default --push latest --branch backup-gh-pages` or at least its `--push` flag?

We have discussed to keep around the `backup-gh-pages` branch, which I agree with, but I'm not sure whether we still want to continue pushing to it.

If yes, then we need to restore the changes you're proposing in this PR (& close it), so that both docs & API docs are published.

If no, then we can remove the `--push` flag from the commands above or (better) remove the commands entirely.

Let me know if I'm missing something, looking forward to merge/close the PR.

**Pull request merged**
