### PR TITLE
chore(cicd): cdk examples and e2e tests for metrics 

### PR DESCRIPTION
**Pull request by flochaz**
## Description of your changes

1. Add global examples based on CDK v2 using our final packages
  ```sh
➜  cdk git:(examples/cdk) npm run cdk deploy

> cdk-app@0.1.0 cdk
> cdk "deploy"

Bundling asset CdkAppStack/MyFunction/Code/Stage...
...
 ✅  CdkAppStack

Stack ARN:
arn:aws:cloudformation:eu-west-1:264025721901:stack/CdkAppStack/aae82b70-5821-11ec-b7f5-023677044a7b
  ```
Screenshot 2021-12-16 at 09 38 06

Screenshot 2021-12-16 at 09 41 15

Screenshot 2021-12-16 at 09 41 48

2. Add an example of e2e test
  ```sh
➜  metrics git:(examples/cdk) npm run test:e2e                        

> @aws-lambda-powertools/metrics@0.0.0 test:e2e
> jest --group=e2eBundling asset ExampleIntegTest/MyFunction/Code/Stage...  ...d640df993fc53f1db8f40962c2c0e5b9900873153fe428478bc48ce9/index.js  10.7kb
⚡ Done in 7ms
[0%] start: Publishing 26112141b6a636c88b4a429c757121777675f5fc2b6437ed1416d6ea26d51f58:current
[100%] success: Published 26112141b6a636c88b4a429c757121777675f5fc2b6437ed1416d6ea26d51f58:current
ExampleIntegTest: creating CloudFormation changeset...
ExampleIntegTest | 0/4 | 09:27:42 | REVIEW_IN_PROGRESS   | AWS::CloudFormation::Stack | ExampleIntegTest User Initiated
ExampleIntegTest | 0/4 | 09:27:48 | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | ExampleIntegTest User Initiated
ExampleIntegTest | 0/4 | 09:27:52 | CREATE_IN_PROGRESS   | AWS::IAM::Role        | MyFunction/ServiceRole (MyFunctionServiceRole3C357FF2) 
ExampleIntegTest | 0/4 | 09:27:53 | CREATE_IN_PROGRESS   | AWS::IAM::Role        | MyFunction/ServiceRole (MyFunctionServiceRole3C357FF2) Resource creation Initiated
ExampleIntegTest | 1/4 | 09:28:08 | CREATE_COMPLETE      | AWS::IAM::Role        | MyFunction/ServiceRole (MyFunctionServiceRole3C357FF2) 
ExampleIntegTest | 1/4 | 09:28:10 | CREATE_IN_PROGRESS   | AWS::IAM::Policy      | MyFunction/ServiceRole/DefaultPolicy (MyFunctionServiceRoleDefaultPolicyB705ABD4) 
ExampleIntegTest | 1/4 | 09:28:11 | CREATE_IN_PROGRESS   | AWS::IAM::Policy      | MyFunction/ServiceRole/DefaultPolicy (MyFunctionServiceRoleDefaultPolicyB705ABD4) Resource creation Initiated
ExampleIntegTest | 2/4 | 09:28:25 | CREATE_COMPLETE      | AWS::IAM::Policy      | MyFunction/ServiceRole/DefaultPolicy (MyFunctionServiceRoleDefaultPolicyB705ABD4) 
ExampleIntegTest | 2/4 | 09:28:27 | CREATE_IN_PROGRESS   | AWS::Lambda::Function | MyFunction (MyFunction3BAA72D1) 
ExampleIntegTest | 2/4 | 09:28:29 | CREATE_IN_PROGRESS   | AWS::Lambda::Function | MyFunction (MyFunction3BAA72D1) Resource creation Initiated
ExampleIntegTest | 3/4 | 09:28:37 | CREATE_COMPLETE      | AWS::Lambda::Function | MyFunction (MyFunction3BAA72D1) 
ExampleIntegTest | 4/4 | 09:28:38 | CREATE_COMPLETE      | AWS::CloudFormation::Stack | ExampleIntegTest 
ExampleIntegTest |   0 | 09:28:42 | DELETE_IN_PROGRESS   | AWS::CloudFormation::Stack | ExampleIntegTest User Initiated
ExampleIntegTest |   0 | 09:28:44 | DELETE_IN_PROGRESS   | AWS::Lambda::Function | MyFunction (MyFunction3BAA72D1) 
ExampleIntegTest |   1 | 09:28:52 | DELETE_COMPLETE      | AWS::Lambda::Function | MyFunction (MyFunction3BAA72D1) 
 PASS  tests/e2e/decorator.test.ts (83.021 s)

Test Suites: 1 passed, 1 of 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        83.5 s, estimated 90 s
Ran all test suites.
   ```

#### Global example

```sh
cd examples/cdk
npm install
npm run build
npm run cdk deploy
```

This will deploy 3 lambdas and invoke them twice (to have one cold start and one warm)

#### Metrics e2e test

Run procedure
```
cd packages/metrics
npm install
npm run test:e2e
```

Doc (might be worth to move that in CONTRIBUTING.md ?)

Tests are under `test` folder and splitted into two categories: Unit tests and e2e tests.

This split happen thanks to [jest-runner-groups](https://www.npmjs.com/package/jest-runner-groups).

Unit tests, under `test/unit` folder, don't need AWS Account to run and can only verify your construct's logic and it's capability to be synthesised to Cloud Formation.

Integration tests, under `test/e2e` folder, will test the deployability (cfn stack deploy) of your construct, potentially its functionality and its deprovisioning capability (cfn stack destroy) and therefore will need an AWS account.

**Unit testing**

**Write**

As mentioned before, tests are splitted thanks to [jest-runner-groups](https://www.npmjs.com/package/jest-runner-groups) and therefore needs to be tagged properly by adding the following comments in your unit test file:

```
/**
 * Tests metrics
 *
 * @group unit/<YOUR CATEGORY>/<YOUR SUB CATEGORY>
 */
```

**Run**

 `npm run test`

You can run selective tests by restricting the group to the one you want. For instance `npx jest --group=unit/metrics/all`.

**e2e testing**

**Write**

As mentioned before, tests are splitted thanks to [jest-runner-groups](https://www.npmjs.com/package/jest-runner-groups) and therefore needs to be tagged properly by adding the following comments in your unit test file:

```
/**
 * Tests data lake catalog
 *
 * @group e2e/<YOUR CATEGORY>/<YOUR SUB CATEGORY>
 */
```

and leverage `aws-cdk` package to programatically deploy and destroy stacks. See `metrics/tests/e2e/decorator.test.ts` as an example.

**Run**

To run unit tests you can either use projen task
* `npm run test:e2e` which will only run jest integ tests
* or jest directly `npx jest --group=e2e`

You can run selective tests by restricting the group to the one you want. For instance `npx jest --group=e2e/other/example`.

Two important env variable can be used:
* `AWS_PROFILE` to use the right credentials
* `DISABLE_TEARDOWN` if you don't want your stack to be destroyed at the end of the test (useful in dev mode when iterating over your code).

Example: `DISABLE_TEARDOWN=true AWS_PROFILE=ara npx jest --group=integ/other/example`

### Related issues, RFCs

#136

### PR status

***Is this ready for review?:*** YES  
***Is it a breaking change?:*** NO

## Checklist

- [x] [My changes meet the tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
- [x] I have performed a *self-review* of my own code
- [x] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [x] I have made corresponding changes to the *documentation*
- [x] My changes generate *no new warnings*
- [x] The *code coverage* hasn't decreased
- [x] I have *added tests* that prove my change is effective and works
- [x] New and existing *unit tests pass* locally and in Github Actions
- [x] Any *dependent changes have been merged and published* in downstream module
- [x] The PR title follows the [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/semantic.yml#L2)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by michaelbrewer** [comment]
@saragerion @ijemmy @flochaz - looks like this lock file was generated by node@16, which will break node@14 users when the want to do `npm test`

**Comment by flochaz** [comment]
> @saragerion @ijemmy @flochaz - looks like this lock file was generated by node@16, which will break node@14 users when the want to do `npm test`

Thx @michaelbrewer. I am opening an issue and will fix asap.

**Comment by dreamorosi** [comment]
> > @saragerion @ijemmy @flochaz - looks like this lock file was generated by node@16, which will break node@14 users when the want to do `npm test`
> 
> Thx @michaelbrewer. I am opening an issue and will fix asap.

For those coming here in the future, the _issue_ was that we recently [started recommending](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/CONTRIBUTING.md#setup) `npm@8.x` for development on the project and those still using a lower version right after the switch got their builds broken for a short while.

Using `node@16.x` and `npm@8.x` should work as expected, if anyone encounters issues with this setup they should please open an issue and provide as many details as possible about the setup.

**Comment by michaelbrewer** [comment]
Sorry about this. I guess things where in flux (so now with the clear contributor guide and the gitpod/CodeSpaces support). It should be clear what the local setup should be.

**Pull request merged**
