### PR TITLE
docs: remove beta warning from batch and idempotency readme

### LINKED ISSUE #1690: Docs: remove `beta` warning from README files
### What were you searching in the docs?

Now that the Bats Processing & Idempotency utilities are GA we should remove the beta warning from the README files ([example](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/batch/README.md?plain=1#L4-L6)) like we did for the docs.

### Is this related to an existing documentation section?

_No response_

### How can we improve?

```Markdown
N/A
```

### Got a suggestion in mind?

_No response_

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

### PR DESCRIPTION
**Pull request by am29d**
## Description of your changes
This PR removes the beta warning from the README in batch and idemoptency utility. 

### Related issues, RFCs

**Issue number:** closes #1690 

## Checklist

- [x] [My changes meet the tenets criteria](https://docs.powertools.aws.dev/lambda-typescript/#tenets)
- [x] I have performed a *self-review* of my own code
- [ ] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [x] I have made corresponding changes to the *documentation*
- [x] My changes generate *no new warnings*
- [ ] I have *added tests* that prove my change is effective and works
- [x] The PR title follows the [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

***Is it a breaking change?:*** NO

- [ ] I have documented the migration process
- [ ] I have added, implemented necessary warnings (if it can live side by side)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by dreamorosi** [comment]
Could you also remove the `(beta)` from this file?

https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/README.md?plain=1#L38

After that, ship it!

**Comment by am29d** [comment]
> Could you also remove the `(beta)` from this file?
> 
> https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/README.md?plain=1#L38
> 
> After that, ship it!

Good catch!

**Comment by am29d** [comment]
Remove more beta flags and added utilities to the main doc page.

**Review by dreamorosi — APPROVED** [review]
Thanks!

**Pull request merged**
